language: python
branches:
  only:
  - master
install:
- pip install pelican ghp-import
script:
- make publish github
env:
  global:
    secure: WmiiTSnvYlIFUeNZxpBocm+2ZWFFdS31s1Hq+7W6vaLrQszY6CKIqWZ0K7VzOgU/TDc6/fHJhy3G5+9ALg6qtJdPEbcACdyjDV3hAfHrgEeX16qLuY9OF3RZnEN70F5PmS1j2Dgc7gbhHxgY5vOFSKybV0kSpncujMs4O5yzRf6stYYQ6OZ0Z8n5dAK8wCIurKFv5Z25pv+rwZeaO4y45R+imegzbUbRBTQhpF7oJTZA0iLoQinfjWl23BlM7XD1dVkc0pgCqFahr9neOrJs7THzJmbRWUR08ZiWBMwr4CgsVGGzai0/ErrN4zSA9qVntL0SPNbVEqDkcsiV28J7T5aZp5FfG2x2rCsAIVTL9hoG00LFZmN/MyyERfxUdPlku+EKSSTsjt+OviGS7CvQlfn6lgLs9xaOMCwOLQbfejETQs8TCzn6h4E90XeyVhUwCg1+MFXPTjdsPhFYwQe90jRcJtdkJY0BvgsOjqA4VjcpssPq+PRPfLulbxxpz05DQ3sM3WB6RUSrFoImSaeHHQsyFV52JASjRtyTvHbetFiF1b7aS49b3/kAOsXlwLSrZ2+zS1lu6mrz0o+nVo5qLlFN0yX/AUrCx4gX4DavvmVe70WUINyAgnNfl6tZW4dMu7EIoUyrUl0otfbzsdfDFwBkGXD42N5OTPOztBJ+HNw=
